### PR TITLE
Update twitterlib.js

### PR DESCRIPTION
**Pull request by pprasanth**
Updated twitter api link version 1 to 1.1, Because twitter has been changed their api version to 1.1 and version 1 will no longer available.

### CODE REVIEW

**Comment by remy** [comment]
Doesn't make any difference, there's no auth, so this won't work at all - it just returns an error message: http://api.twitter.com/1.1/statuses/user_timeline.json?screen_name=rem

**Comment by pprasanth** [comment]
But version http://api.twitter.com/1/statuses/user_timeline.json?screen_name=rem doesn't support anymore.

it showing :- 
{"errors": [{"message": "The Twitter REST API v1 is no longer active. Please migrate to API v1.1. https://dev.twitter.com/docs/api/1.1/overview.", "code": 68}]}

**Comment by remy** [comment]
Yeah, the whole thing is borked sadly. Twitter's auth requirement has
killed projects like this.

I'm investigating work arounds, but none are nice and none quite do what I
want.

**Comment by pprasanth** [comment]
Could you please look on this article https://dev.twitter.com/docs/auth/oauth/single-user-with-examples

**Comment by pprasanth** [comment]
please check this link also, https://dev.twitter.com/docs/twitter-libraries

https://github.com/mynetx/codebird-js is OAuth based javascript library. You can use this library for example. could you please update it asap.

Update it to your code to : http://remy.github.io/twitterlib/twitterlib.js

**Comment by remy** [comment]
Feel free to check those examples out in more detail.  I've been through
the docs, and I know about codebird-js.  They **all** require a server to
perform their tasks.  twitterlib.js was a serverless library.

codebird looks initially like it does it all in the client, but dig around
a little deeper, and you'll see their hitting their own machines.

**Comment by pprasanth** [comment]
Anyway, thanks. Please update your code if you got anything tricky!. :)

**Pull request closed without merging**
